# Generated by Django 4.2 on 2023-05-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_topic',
            name='auction_topic_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
